version: '27.4.0'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    restart: unless-stopped